name: KMP library compilation check

on:
  pull_request:
    branches:
    - master
    - develop

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: zulu
    - name: Check
      run: ./local-check.sh
